/**
 * Centralized API Route Endpoints Registry
 */
export const ENDPOINTS = {
  AUTH: {
    LOGIN: "/api/auth_login.php",
    LOGOUT: "/api/auth_logout.php",
    CHECK: "/api/auth_check.php",
  },
  USER: {
    GET_USERS: "/api/get_users.php",
    POST_USERS: "/api/post_users.php",
    GET_PROFILE: "/api/get_profile.php",
    POST_PROFILE: "/api/post_profile.php",
    UPLOAD_PHOTO: "/api/upload_photo.php",
  },
  SIEM: {
    GET_LOGS: "/api/get_siem_logs.php",
    GET_LIVE_LOGS: "/api/get_siem_live_logs.php",
    POST_ACTION: "/api/post_siem_logs.php",
  },
  SOC: {
    GET_INCIDENTS: "/api/get_soc_incidents.php",
    POST_INCIDENTS: "/api/post_soc_incidents.php",
  },
  RESPONDER: {
    GET_RESPONDER: "/api/get_responder.php",
    POST_RESPONDER: "/api/post_responder.php",
    GET_AUTOMATION: "/api/get_automation.php",
    POST_INSTALL: "/api/post_install_automation.php",
  },
  REPORTS: {
    TRAFFIC: "/api/get_report_traffic.php",
    BANDWIDTH: "/api/get_report_bandwidth.php",
    BRUTEFORCE: "/api/get_report_bruteforce.php",
    DDOS: "/api/get_report_ddos.php",
    ANOMALY: "/api/get_report_anomaly.php",
    APPLICATIONS: "/api/get_report_applications.php",
    ASSET_DISCOVERY: "/api/get_report_asset_discovery.php",
    COMPLIANCE: "/api/get_report_compliance.php",
    CONFIG_CHANGES: "/api/get_report_config_changes.php",
    DNS_ATTACKS: "/api/get_report_dns_attacks.php",
    ENDPOINT_ACTIVITY: "/api/get_report_endpoint_activity.php",
    MALWARE: "/api/get_report_malware.php",
    REMOTE_ACCESS: "/api/get_report_remote_access.php",
    SECURITY_ANALYSIS: "/api/get_report_security_analysis.php",
    THREAT_HUNTING: "/api/get_report_threat_hunting.php",
    USER_ACTIVITY: "/api/get_report_user_activity.php",
    VULNERABILITY: "/api/get_report_vulnerability.php",
    META: "/api/get_reports_meta.php",
    FFLOW: "/api/get_fflow.php",
  },
  DEVICES: {
    GET_DEVICES: "/api/get_devices.php",
    POST_DEVICES: "/api/post_devices.php",
    GET_CONFIG_BACKUP: "/api/get_config_backup.php",
    POST_CONFIG_BACKUP: "/api/post_config_backup.php",
  },
  AVAILABILITY: {
    GET_AVAILABILITY: "/api/get_availability.php",
    POST_AVAILABILITY: "/api/post_availability.php",
    GET_REPORTS: "/api/get_availability_reports.php",
  },
  THREAT: {
    IPS: "/api/get_ips.php",
    MALWARE_GET: "/api/get_malware.php",
    MALWARE_POST: "/api/post_malware.php",
    INTEL_GET: "/api/get_threat_intel.php",
    INTEL_POST: "/api/post_threat_intel.php",
    TRAFFIC_ANALYZER: "/api/get_traffic.php",
    VULN_SCAN_POST: "/api/post_scan.php",
    SEARCH: "/api/get_search.php",
  },
  MONITOR: {
    MONITOR: "/api/get_monitor.php",
    IPAM_GET: "/api/get_ipam.php",
    IPAM_POST: "/api/post_ipam.php",
    RESOURCES: "/api/get_resources.php",
    HOME: "/api/get_home.php",
    NAV_DATA: "/api/get_nav_data.php",
    MAPS_GET: "/api/get_maps.php",
    MAPS_POST: "/api/post_maps.php",
  },
};
